### ISSUE TITLE
requestPaymentOfChargeWithUUID completion handler

### ISSUE THREAD

**Issue by DanieleCux** [satispay/app-extension-ios#2]
Hi, I noticed that I could not discriminate the case in which a user accessed the Satispay app from the case in which a user canceled the open satispay app action. I suggest to refactor the method to:
```

- (void)requestPaymentOfChargeWithUUID:(nonnull NSString *)UUID
                    fromViewController:(nonnull UIViewController *)sourceViewController
                                sender:(nullable id)sender
                            completion:(nullable void (^)(NSError * __nullable error, BOOL completed))completion {

    NSParameterAssert(UUID != nil);
    NSParameterAssert(sourceViewController != nil);

    NSItemProvider * itemProvider = [[NSItemProvider alloc] initWithItem:@{ SatispayPaymentExtensionChargeUUIDKey: UUID }
                                                          typeIdentifier:SatispayPaymentExtensionChargeTypeIdentifier];

    NSExtensionItem * extensionItem = [NSExtensionItem new];
    extensionItem.attachments = @[ itemProvider ];

    UIActivityViewController * controller = [self activityViewControllerForExtensionItem:extensionItem
                                                                                  sender:sender];

    controller.completionWithItemsHandler = ^(NSString * activityType, BOOL completed, NSArray * returnedItems, NSError * activityError) {

        if (activityError) {
            if (completion) {
                completion(activityError, completed);
            }

            return;
        }

        if (completion) {
            completion(nil, completed);
        }

        return;

    };

    [sourceViewController presentViewController:controller animated:YES completion:nil];

}
```

So that the app using the extension can know if the user actually used the satispay app extension

**Comment by pNre** [comment]
Ciao, al momento sconsigliamo l'utilizzo dell'app extension ma suggeriamo di utilizzare l'[url scheme satispay://](https://s3-eu-west-1.amazonaws.com/docs.online.satispay.com/index.html#section/Mobile-App/App-URL-schemes) per garantire una migliore esperienza d'uso.

**Comment by DanieleCux** [comment]
Ciao,
grazie per la velocità nella risposta: non avevo capito capito che l'app extension fosse la seconda scelta; avevo inteso il 

> "If for any reason the Mobile SDK cannot be integrated, the following Url_Scheme to invoke the Satispay App are available"

come un'indicazione rispetto all'usare intento l'app extension, e poi se quella non è disponibile direttamente l'url scheme. In effetti questo è quello che ho trovato anche nel codice di esempio (ho controllato però solo l'esempio in objective-c).

Vi chiedo una cosa allora:
per completezza ho testato anche il giro che utilizza l'app-scheme con l'url di callback. Ho visto che ci sono dei casi in cui la mia app non viene richiamata. In particolare questo avviene quando l'app satispay non è già in esecuzione al momento in cui la chiamo. Questo problema risulta anche a voi? Io ho fatto i test con l'app di stage, ma ho riscontrato questo problema sia su un iPhone 5 con iOS 10.3.3, sia su iPhone 6s e su iPhone X (entrambi con iOS 12.0.1)

**Comment by pNre** [comment]
> Ciao,
> grazie per la velocità nella risposta: non avevo capito capito che l'app extension fosse la seconda scelta; avevo inteso il
> 
> > "If for any reason the Mobile SDK cannot be integrated, the following Url_Scheme to invoke the Satispay App are available"
> 
> come un'indicazione rispetto all'usare intento l'app extension, e poi se quella non è disponibile direttamente l'url scheme. In effetti questo è quello che ho trovato anche nel codice di esempio (ho controllato però solo l'esempio in objective-c).
> 

Hai ragione, quella documentazione è da aggiornare.

> Vi chiedo una cosa allora:
> per completezza ho testato anche il giro che utilizza l'app-scheme con l'url di callback. Ho visto che ci sono dei casi in cui la mia app non viene richiamata. In particolare questo avviene quando l'app satispay non è già in esecuzione al momento in cui la chiamo. Questo problema risulta anche a voi? Io ho fatto i test con l'app di stage, ma ho riscontrato questo problema sia su un iPhone 5 con iOS 10.3.3, sia su iPhone 6s e su iPhone X (entrambi con iOS 12.0.1)

Questo è un bug e verrà corretto in un prossimo rilascio mentre la versione di staging aggiornata sarà disponibile in giornata.

**Comment by DanieleCux** [comment]
Ok, grazie mille
