### ISSUE TITLE
Url scheme non funziona se non si è già inserito il PIN

### ISSUE THREAD

**Issue by DottorPagliaccius** [satispay/app-extension-ios#3]
Ciao,
per gestire il pagamento dalla mia app una volta creato il charge utilizzo l'url 

satispay://external/generic/charge?token={chargeId}

che funziona perfettamente se ho già l'app aperta con il pin già inserito, ma se così non è una volta inserito il pin non c'è il redirect verso la pagina della transazione e non sembra esserci modo di risalirvi... dove sbaglio?

M.B.

**Comment by pNre** [comment]
Ciao, assicurati di utilizzare l'url scheme di staging se stai utilizzando l'app di staging per i test.
- `satispay://` -> produzione
- `satispay-stag://` -> staging

Se dovessi continuare a riscontrare problemi puoi scrivere una mail al support che saprà sicuramente assisterti al meglio.
